export const localeText = {
  selectAll: 'Seleccionar Todo',
  selectAllSearchResults: 'Seleccionar Todos los Resultados de la Búsqueda',
  searchOoo: 'Buscar...',
  blanks: 'Blancos',
  noMatches: 'Sin Coincidencias',
  filterOoo: 'Filtrar...',
  equals: 'Igual',
  notEqual: 'No Igual',
  blank: 'En Blanco',
  notBlank: 'No en Blanco',
  empty: 'Elija uno',
  lessThan: 'Menos que',
  greaterThan: 'Mayor que',
  lessThanOrEqual: 'Menos o igual',
  greaterThanOrEqual: 'Mayor o igual',
  inRange: 'En rango',
  inRangeStart: 'desde',
  inRangeEnd: 'hasta',
  contains: 'Contiene',
  notContains: 'No contiene',
  startsWith: 'Comienza con',
  endsWith: 'Termina con',
  dateFormatOoo: 'dd-mm-yyyy',
  andCondition: 'Y',
  orCondition: 'O',
  applyFilter: 'Aplicar',
  resetFilter: 'Restablecer',
  clearFilter: 'Limpiar',
  cancelFilter: 'Cancelar',
  loadingOoo: 'Cargando...',
  noRowsToShow: 'No hay filas para mostrar',
  enabled: 'Habilitado',
  pinColumn: 'Fijar Columna',
  pinLeft: 'Fijar Izquierda',
  pinRight: 'Fijar Derecha',
  noPin: 'Sin Fijar',
  valueAggregation: 'Valor de Agregación',
  autosizeThiscolumn: 'Ajustar esta Columna',
  autosizeAllColumns: 'Ajustar Todas las Columnas',
  groupBy: 'Agrupar por',
  ungroupBy: 'Desagrupar por',
  resetColumns: 'Restablecer Columnas',
  expandAll: 'Expandir Todo',
  collapseAll: 'Colapsar Todo',
  copy: 'Copiar',
  ctrlC: 'Ctrl+C',
  copyWithHeaders: 'Copiar con Encabezados',
  paste: 'Pegar',
  ctrlV: 'Ctrl+V',
  export: 'Exportar',
  csvExport: 'Exportar a CSV',
  excelExport: 'Exportar a Excel (.xlsx)',
  sum: 'Suma',
  min: 'Mín',
  max: 'Máx',
  none: 'Ninguno',
  count: 'Cuenta',
  avg: 'Prom',
  filteredRows: 'Filas filtradas',
  selectedRows: 'Filas seleccionadas',
  totalRows: 'Total filas',
  totalAndFilteredRows: 'Filas',
  more: 'Más',
  to: 'a',
  of: 'de',
  page: 'Página',
  nextPage: 'Siguiente Página',
  lastPage: 'Última Página',
  firstPage: 'Primera Página',
  previousPage: 'Página Anterior',
};
